let date = new Date();
console.log(date);
console.log(date.getTime());
// date.setDate(13);
console.log(date.getDate());
console.log(date.toString());
console.log(date.toDateString());
console.log(date.toTimeString());
console.log(date.toLocaleString());
console.log(date.toLocaleDateString());
console.log(date.toLocaleTimeString());